[package]
name = "rpi-management-api"
version = "0.1.0"
authors = ["Damien Lecan <dev@dlecan.com>"]

[dependencies]
rustless = { git = "https://github.com/rustless/rustless" }
rustc-serialize = "*"
hyper = "*"
iron = "*"
valico = "*"